name: Postman Workflow Collection

on : 
 push:
     branches:[main]
 workflow_dispatch: 
    Schedule: 
      -cron: 30:02:*:*:* #8:00 am IST (default timezone is UTC) 

jobs: 
  run-postman-test:
  run-on: ubuntu-latest

steps: 
-name : Checkout Code
  uses : actions/checkout@v4.2.2

-name: Setup Node
  uses: actions/setup-node@v3.9.1
  with: 
  node-version : '22'

name: install newman and report 
run : |
      npm install -g newman 
      npm install -g newman-reporter-htmlextra

name : Run Collection
run : | 
      newman run 'Inwarranty-flow\ Collection.postman_collection.json' \
      -e QA.postman_environment.json \
      -d testData.csv \
      -r cli, htmlextra

      

  
      
 
